version: '3'
services:

  rabbitmq1:
    image: rabbitmq:3.9.14-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_BASE=/var/lib/rabbitmq
      - RABBITMQ_CONFIG_FILES=/var/lib/rabbitmq/rabbitmq.conf
    volumes:
      - /docker/rabbitmqnode1/:/var/lib/rabbitmq/

  rabbitmq2:
    image: rabbitmq:3.9.14-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_BASE=/var/lib/rabbitmq
      - RABBITMQ_CONFIG_FILES=/var/lib/rabbitmq/rabbitmq.conf
    volumes:
      - /docker/rabbitmqnode2/:/var/lib/rabbitmq/
      - /docker/rabbitmqcluster/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3.9.14-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_BASE=/var/lib/rabbitmq
      - RABBITMQ_CONFIG_FILES=/var/lib/rabbitmq/rabbitmq.conf
    volumes:
      - /docker/rabbitmqnode3/:/var/lib/rabbitmq/
      - /docker/rabbitmqcluster/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  haproxy:
    image: haproxy
    volumes:
      - /docker/rabbitmqcluster/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 20000:15672
      - 5672:5672
